import type { GTMDataLayerOutput, GTMStageOutput, JourneyDefinition, PlatformConfig } from '../../../types/journey';
import { getActionPrimitive } from '../actionPrimitives';

function generateStageSnippet(
  stageLabel: string,
  stageOrder: number,
  sampleUrl: string | null,
  actions: string[],
  platforms: PlatformConfig[],
): GTMStageOutput {
  const activePlatformNames = platforms
    .filter((p) => p.is_active)
    .map((p) => p.platform.toUpperCase().replace('_', ' '))
    .join(', ');

  const lines: string[] = [];
  const comments: string[] = [];

  lines.push(`// ${'='.repeat(61)}`);
  lines.push(`// STAGE: ${stageLabel}`);
  if (sampleUrl) lines.push(`// URL: ${sampleUrl}`);
  lines.push(`// Events: ${actions.join(', ') || 'page_view'}`);
  lines.push(`// Platforms: ${activePlatformNames || 'None selected'}`);
  lines.push(`// Generated by Atlas — do not edit directly`);
  lines.push(`// ${'='.repeat(61)}`);
  lines.push('');
  lines.push('window.dataLayer = window.dataLayer || [];');
  lines.push('');

  if (actions.length === 0) {
    lines.push('// No conversion actions are tracked on this page.');
    lines.push('// Atlas will still check that page_view fires and base tags are loaded.');
    return { stage_label: stageLabel, stage_order: stageOrder, sample_url: sampleUrl, code_snippet: lines.join('\n'), comments };
  }

  for (const actionKey of actions) {
    const primitive = getActionPrimitive(actionKey);
    if (!primitive) continue;

    if (actionKey === 'ad_landing') {
      lines.push('// Landing page: Atlas will check that click IDs (gclid, fbclid) are captured in cookies.');
      lines.push('// No additional dataLayer push is required here — GTM handles this automatically.');
      comments.push('Ensure GTM is loaded on this page. The gclid/fbclid params will be auto-captured.');
      continue;
    }

    lines.push(`// --- ${primitive.label} ---`);

    if (actionKey === 'purchase') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'purchase',`);
      lines.push(`  ecommerce: {`);
      lines.push(`    transaction_id: '{{ORDER_ID}}',         // REQUIRED: Your unique order ID`);
      lines.push(`    value: {{ORDER_TOTAL}},                  // REQUIRED: Total order value (number)`);
      lines.push(`    currency: '{{CURRENCY_CODE}}',           // REQUIRED: e.g., 'USD', 'SGD'`);
      lines.push(`    tax: {{TAX_AMOUNT}},                     // Optional: Tax amount`);
      lines.push(`    shipping: {{SHIPPING_COST}},             // Optional: Shipping cost`);
      lines.push(`    coupon: '{{COUPON_CODE}}',               // Optional: Coupon used`);
      lines.push(`    items: [`);
      lines.push(`      {`);
      lines.push(`        item_id: '{{PRODUCT_SKU}}',          // Product ID/SKU`);
      lines.push(`        item_name: '{{PRODUCT_NAME}}',       // Product name`);
      lines.push(`        price: {{PRODUCT_PRICE}},            // Unit price`);
      lines.push(`        quantity: {{PRODUCT_QUANTITY}}        // Quantity purchased`);
      lines.push(`      }`);
      lines.push(`      // Repeat for each product in the order`);
      lines.push(`    ]`);
      lines.push(`  },`);
      lines.push(`  // Enhanced Conversions data (for Google Ads + Meta CAPI)`);
      lines.push(`  user_data: {`);
      lines.push(`    email: '{{CUSTOMER_EMAIL}}',             // Optional: Hashed automatically by GTM`);
      lines.push(`    phone_number: '{{CUSTOMER_PHONE}}'       // Optional: Hashed automatically by GTM`);
      lines.push(`  }`);
      lines.push(`});`);
    } else if (actionKey === 'add_to_cart') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'add_to_cart',`);
      lines.push(`  ecommerce: {`);
      lines.push(`    value: {{ITEM_VALUE}},                   // REQUIRED: Value of items added`);
      lines.push(`    currency: '{{CURRENCY_CODE}}',           // REQUIRED: e.g., 'USD'`);
      lines.push(`    items: [{`);
      lines.push(`      item_id: '{{PRODUCT_SKU}}',`);
      lines.push(`      item_name: '{{PRODUCT_NAME}}',`);
      lines.push(`      price: {{PRODUCT_PRICE}},`);
      lines.push(`      quantity: {{QUANTITY}}`);
      lines.push(`    }]`);
      lines.push(`  }`);
      lines.push(`});`);
    } else if (actionKey === 'begin_checkout') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'begin_checkout',`);
      lines.push(`  ecommerce: {`);
      lines.push(`    value: {{CART_VALUE}},                   // REQUIRED: Total cart value`);
      lines.push(`    currency: '{{CURRENCY_CODE}}',           // REQUIRED: e.g., 'USD'`);
      lines.push(`    coupon: '{{COUPON_CODE}}',               // Optional: Applied coupon`);
      lines.push(`    items: [/* ... products in cart ... */]`);
      lines.push(`  }`);
      lines.push(`});`);
    } else if (actionKey === 'generate_lead') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'generate_lead',`);
      lines.push(`  form_id: '{{FORM_ID}}',                   // REQUIRED: e.g., 'contact_form_main'`);
      lines.push(`  value: {{LEAD_VALUE}},                     // Optional: Estimated lead value`);
      lines.push(`  currency: '{{CURRENCY_CODE}}',             // Optional: e.g., 'USD'`);
      lines.push(`  user_data: {`);
      lines.push(`    email: '{{LEAD_EMAIL}}',                 // Optional: Will be hashed by GTM`);
      lines.push(`    phone_number: '{{LEAD_PHONE}}'           // Optional: Will be hashed by GTM`);
      lines.push(`  }`);
      lines.push(`});`);
    } else if (actionKey === 'sign_up') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'sign_up',`);
      lines.push(`  method: '{{SIGNUP_METHOD}}',               // REQUIRED: e.g., 'email', 'google'`);
      lines.push(`  user_id: '{{USER_ID}}'                     // Optional: Your system user ID`);
      lines.push(`});`);
    } else if (actionKey === 'view_item') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'view_item',`);
      lines.push(`  ecommerce: {`);
      lines.push(`    value: {{PRODUCT_PRICE}},                // Optional: Product price`);
      lines.push(`    currency: '{{CURRENCY_CODE}}',           // Optional: e.g., 'USD'`);
      lines.push(`    items: [{`);
      lines.push(`      item_id: '{{PRODUCT_SKU}}',            // REQUIRED: Product ID/SKU`);
      lines.push(`      item_name: '{{PRODUCT_NAME}}',         // REQUIRED: Product name`);
      lines.push(`      price: {{PRODUCT_PRICE}}`);
      lines.push(`    }]`);
      lines.push(`  }`);
      lines.push(`});`);
    } else if (actionKey === 'view_item_list') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'view_item_list',`);
      lines.push(`  ecommerce: {`);
      lines.push(`    item_list_name: '{{CATEGORY_NAME}}',     // REQUIRED: e.g., 'Summer Collection'`);
      lines.push(`    items: [/* ... products in the list ... */]`);
      lines.push(`  }`);
      lines.push(`});`);
    } else if (actionKey === 'search') {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: 'search',`);
      lines.push(`  search_term: '{{SEARCH_QUERY}}'            // REQUIRED: What the user searched for`);
      lines.push(`});`);
    } else {
      lines.push(`window.dataLayer.push({`);
      lines.push(`  event: '${actionKey}',`);
      lines.push(`  // Add relevant parameters for this event`);
      lines.push(`});`);
    }

    lines.push('');
  }

  return {
    stage_label: stageLabel,
    stage_order: stageOrder,
    sample_url: sampleUrl,
    code_snippet: lines.join('\n'),
    comments,
  };
}

const GTM_GLOBAL_SETUP = `<!-- Google Tag Manager — place in <head> as high as possible -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','{{GTM_CONTAINER_ID}}');</script>
<!-- End Google Tag Manager -->

<!-- Google Tag Manager (noscript) — place immediately after <body> -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id={{GTM_CONTAINER_ID}}"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<!-- Replace {{GTM_CONTAINER_ID}} with your GTM container ID, e.g. GTM-XXXXXXX -->`;

export function generateGTMDataLayer(journey: JourneyDefinition, platforms: PlatformConfig[]): GTMDataLayerOutput {
  const stages: GTMStageOutput[] = journey.stages
    .sort((a, b) => a.stage_order - b.stage_order)
    .map((stage) =>
      generateStageSnippet(
        stage.label,
        stage.stage_order,
        stage.sample_url,
        stage.actions,
        platforms,
      ),
    );

  return { stages, global_setup: GTM_GLOBAL_SETUP };
}
